name: Daily Automation Run

on:
  schedule:
    - cron: '30 4 * * *'  # 1 PM IST = 7:30 AM UTC
  workflow_dispatch:      # This allows manual trigger from GitHub UI

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (or Java, Python, etc. depending on your project)
      uses: actions/setup-node@v3
      with:
        node-version: '18'   # Change as per your environment

    - name: Install dependencies
      run: npm install      # Or mvn install / pip install -r requirements.txt

    - name: Run automation tests
      run: npx playwright test       # Or the test command for your tool (e.g., `npx playwright test`, `mvn test`, etc.)
